# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "tabit"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thomas Boerger", "Tim Rudat"]
  s.date = "2012-04-30"
  s.email = "thomas.boerger@langwhich.com"
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md"
  ]
  s.files = [
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.md",
    "README.md",
    "Rakefile",
    "init.rb",
    "lib/tabit.rb",
    "lib/tabit/builder.rb",
    "lib/tabit/cell.rb",
    "lib/tabit/config.rb",
    "lib/tabit/helper.rb",
    "lib/tabit/item.rb",
    "lib/tabit/railtie.rb",
    "lib/tabit/version.rb",
    "tabit.gemspec"
  ]
  s.homepage = "https://github.com/Langwhich/tabit"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "Tabit is a simple tab menu generator"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<active_link_to>, ["~> 1.0.0"])
      s.add_development_dependency(%q<redcarpet>, ["~> 2.1.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<active_link_to>, ["~> 1.0.0"])
      s.add_dependency(%q<redcarpet>, ["~> 2.1.0"])
      s.add_dependency(%q<yard>, ["~> 0.7.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<active_link_to>, ["~> 1.0.0"])
    s.add_dependency(%q<redcarpet>, ["~> 2.1.0"])
    s.add_dependency(%q<yard>, ["~> 0.7.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

